Create mobile version
piero-vic/react-capstone pull request #1
Opened 2021-12-23 20:23 UTC by piero-vic

# Create mobile version
- Setup routes.
- Setup redux.
- Create `Home` and `Details` componenets.
- Fetch data from APIs.
- Implement tests.

2021-12-23 23:45 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @piero-vic, 

Good job so far!
The project is deployed properly, the home and detail page works as expected :+1: 
There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️

- [ ] Great presentation so far, but you should also highlight some interesting piece of code or something you built that you are very proud of.

_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 23:45 UTC, sinansevgi commented on src/components/Home.js
> +
- [ ] The Home page should have a list of categories that could be filtered using given parameters (state name, etc..)

From the project requirements. :arrow_down: 
> - When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.

> - You should filter the data that you retrieve from the API using a Filter stateless component.

2021-12-23 23:45 UTC, sinansevgi commented on src/tests/Home.test.js
> +describe('Details test', () => {
- [ ] This should be `Home test`

2021-12-23 23:45 UTC, sinansevgi commented on src/tests/Home.test.js
> +
- [ ] It will be better if you add more integration tests. (Example: It should display state name, It should display state population, It should have a link to details component, etc...) (You should also add tests for your TBD `filter` component)

2021-12-23 23:45 UTC, sinansevgi commented on src/tests/Details.test.js
> +
- [ ] It will be better if you add more integration tests. (Example: It should display TODAY'S COVID INFORMATION section, It should display Capital City, etc...)

2021-12-23 23:45 UTC, sinansevgi commented on src/components/Details.js
> +const Details = (props) => {
- [ ] If you are passing props to a component, it is good practice to validate prop types. Without having PropTypes or some form of type checking, we run into the risk of passing in a wrong data type to a component, which could cause a crash or some unexpected behaviors in our applications.

2021-12-23 23:45 UTC, sinansevgi commented on src/components/Details.js
> +/* eslint-disable react/prop-types */
- [ ] Please try to solve linter errors instead of suppressing the warnings.

2021-12-23 23:45 UTC, sinansevgi commented on src/components/Home.js
> +
[Optional]

- [ ] In react applications we usually use the [Model–view–viewmodel design pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel), Which means that you should have a component (container) for handling data and another one for rendering data. This way your application will be easier to test and debug.

For example:
HomeContainer component gets data from the store, prepares data, and passes it to a Home Component which only renders data.

2021-12-24 18:20 UTC, hiromataba approved these changes
# Status: Approved :tada:  :champagne:  :confetti_ball: 
Hi @piero-vic     :wave: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your README file looks very professional :+1: 
- Your Design looks awesome, keep rocking :rocket: 
![image](https://user-images.githubusercontent.com/75126481/147368580-7e39fb82-855a-4a7f-84c1-6cfcd8f25ce2.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 18:57 UTC, merged